import { WeatherCondition } from '../types';

export const DEFAULT_WEATHER_CITIES: Record<string, WeatherCondition> = {
  'cape town': {
    city: 'Cape Town',
    province: 'Western Cape, South Africa',
    temp: 21,
    condition: 'Partly Cloudy',
    icon: 'partly-cloudy',
    high: 24,
    low: 15,
    humidity: 64,
    windSpeed: 28,
    feelsLike: 20,
    uvIndex: 6,
    airQuality: 'Good (32)',
    precipitationChance: 10,
    hourly: [
      { time: 'Now', temp: 21, icon: 'partly-cloudy', pop: 10 },
      { time: '14:00', temp: 23, icon: 'sun', pop: 5 },
      { time: '15:00', temp: 24, icon: 'sun', pop: 5 },
      { time: '16:00', temp: 22, icon: 'sun', pop: 10 },
      { time: '17:00', temp: 20, icon: 'partly-cloudy', pop: 15 },
      { time: '18:00', temp: 18, icon: 'cloud', pop: 20 },
      { time: '19:00', temp: 17, icon: 'cloud', pop: 25 },
      { time: '20:00', temp: 16, icon: 'moon', pop: 20 },
    ],
    daily: [
      { day: 'Today', condition: 'Partly Cloudy', icon: 'partly-cloudy', high: 24, low: 15, pop: 10 },
      { day: 'Sat', condition: 'Sunny & Crisp', icon: 'sun', high: 26, low: 16, pop: 0 },
      { day: 'Sun', condition: 'Fresh Breeze', icon: 'wind', high: 23, low: 14, pop: 15 },
      { day: 'Mon', condition: 'Scattered Showers', icon: 'rain', high: 19, low: 13, pop: 60 },
      { day: 'Tue', condition: 'Clearing Skies', icon: 'partly-cloudy', high: 21, low: 14, pop: 20 },
      { day: 'Wed', condition: 'Warm & Sunny', icon: 'sun', high: 27, low: 16, pop: 5 },
      { day: 'Thu', condition: 'Moderate Gale', icon: 'wind', high: 22, low: 15, pop: 10 },
    ],
  },
  'johannesburg': {
    city: 'Johannesburg',
    province: 'Gauteng, South Africa',
    temp: 26,
    condition: 'Afternoon Thunderstorm',
    icon: 'storm',
    high: 28,
    low: 14,
    humidity: 58,
    windSpeed: 16,
    feelsLike: 27,
    uvIndex: 9,
    airQuality: 'Moderate (54)',
    precipitationChance: 70,
    hourly: [
      { time: 'Now', temp: 26, icon: 'storm', pop: 70 },
      { time: '14:00', temp: 25, icon: 'storm', pop: 85 },
      { time: '15:00', temp: 22, icon: 'rain', pop: 60 },
      { time: '16:00', temp: 21, icon: 'cloud', pop: 30 },
      { time: '17:00', temp: 20, icon: 'partly-cloudy', pop: 15 },
      { time: '18:00', temp: 19, icon: 'partly-cloudy', pop: 10 },
      { time: '19:00', temp: 17, icon: 'moon', pop: 5 },
      { time: '20:00', temp: 16, icon: 'moon', pop: 0 },
    ],
    daily: [
      { day: 'Today', condition: 'Thunderstorms', icon: 'storm', high: 28, low: 14, pop: 70 },
      { day: 'Sat', condition: 'Sunny Highveld', icon: 'sun', high: 29, low: 15, pop: 10 },
      { day: 'Sun', condition: 'Isolated Showers', icon: 'rain', high: 27, low: 14, pop: 40 },
      { day: 'Mon', condition: 'Clear Sky', icon: 'sun', high: 30, low: 16, pop: 0 },
      { day: 'Tue', condition: 'Partly Cloudy', icon: 'partly-cloudy', high: 28, low: 15, pop: 20 },
      { day: 'Wed', condition: 'Evening Storms', icon: 'storm', high: 27, low: 14, pop: 65 },
      { day: 'Thu', condition: 'Sunny', icon: 'sun', high: 29, low: 15, pop: 5 },
    ],
  },
  'durban': {
    city: 'Durban',
    province: 'KwaZulu-Natal, South Africa',
    temp: 28,
    condition: 'Humid & Sunny',
    icon: 'sun',
    high: 30,
    low: 21,
    humidity: 78,
    windSpeed: 22,
    feelsLike: 32,
    uvIndex: 10,
    airQuality: 'Good (28)',
    precipitationChance: 15,
    hourly: [
      { time: 'Now', temp: 28, icon: 'sun', pop: 15 },
      { time: '14:00', temp: 30, icon: 'sun', pop: 10 },
      { time: '15:00', temp: 29, icon: 'sun', pop: 10 },
      { time: '16:00', temp: 28, icon: 'partly-cloudy', pop: 20 },
      { time: '17:00', temp: 26, icon: 'partly-cloudy', pop: 20 },
      { time: '18:00', temp: 24, icon: 'moon', pop: 15 },
      { time: '19:00', temp: 23, icon: 'moon', pop: 10 },
      { time: '20:00', temp: 22, icon: 'moon', pop: 10 },
    ],
    daily: [
      { day: 'Today', condition: 'Tropical Sun', icon: 'sun', high: 30, low: 21, pop: 15 },
      { day: 'Sat', condition: 'Warm & Humid', icon: 'sun', high: 31, low: 22, pop: 20 },
      { day: 'Sun', condition: 'Coastal Wind', icon: 'wind', high: 28, low: 20, pop: 30 },
      { day: 'Mon', condition: 'Passing Showers', icon: 'rain', high: 26, low: 20, pop: 55 },
      { day: 'Tue', condition: 'Bright Sunshine', icon: 'sun', high: 29, low: 21, pop: 10 },
      { day: 'Wed', condition: 'Humid & Warm', icon: 'sun', high: 30, low: 22, pop: 15 },
      { day: 'Thu', condition: 'Partly Cloudy', icon: 'partly-cloudy', high: 29, low: 21, pop: 25 },
    ],
  },
  'pretoria': {
    city: 'Pretoria',
    province: 'Gauteng, South Africa',
    temp: 29,
    condition: 'Sunny & Warm',
    icon: 'sun',
    high: 31,
    low: 16,
    humidity: 45,
    windSpeed: 12,
    feelsLike: 30,
    uvIndex: 9,
    airQuality: 'Moderate (48)',
    precipitationChance: 10,
    hourly: [
      { time: 'Now', temp: 29, icon: 'sun', pop: 10 },
      { time: '14:00', temp: 31, icon: 'sun', pop: 5 },
      { time: '15:00', temp: 31, icon: 'sun', pop: 5 },
      { time: '16:00', temp: 30, icon: 'sun', pop: 10 },
      { time: '17:00', temp: 27, icon: 'sun', pop: 10 },
      { time: '18:00', temp: 24, icon: 'partly-cloudy', pop: 15 },
      { time: '19:00', temp: 21, icon: 'moon', pop: 5 },
      { time: '20:00', temp: 19, icon: 'moon', pop: 0 },
    ],
    daily: [
      { day: 'Today', condition: 'Sunny & Warm', icon: 'sun', high: 31, low: 16, pop: 10 },
      { day: 'Sat', condition: 'Hot Jacaranda Sun', icon: 'sun', high: 32, low: 17, pop: 5 },
      { day: 'Sun', condition: 'Afternoon Cloud', icon: 'partly-cloudy', high: 30, low: 16, pop: 20 },
      { day: 'Mon', condition: 'Clear Sky', icon: 'sun', high: 31, low: 17, pop: 0 },
      { day: 'Tue', condition: 'Warm & Dry', icon: 'sun', high: 33, low: 18, pop: 10 },
      { day: 'Wed', condition: 'Scattered Storms', icon: 'storm', high: 28, low: 16, pop: 50 },
      { day: 'Thu', condition: 'Sunny Skies', icon: 'sun', high: 30, low: 16, pop: 5 },
    ],
  },
  'stellenbosch': {
    city: 'Stellenbosch',
    province: 'Western Cape, South Africa',
    temp: 23,
    condition: 'Clear Sky',
    icon: 'sun',
    high: 27,
    low: 13,
    humidity: 52,
    windSpeed: 14,
    feelsLike: 23,
    uvIndex: 7,
    airQuality: 'Excellent (18)',
    precipitationChance: 5,
    hourly: [
      { time: 'Now', temp: 23, icon: 'sun', pop: 5 },
      { time: '14:00', temp: 26, icon: 'sun', pop: 0 },
      { time: '15:00', temp: 27, icon: 'sun', pop: 0 },
      { time: '16:00', temp: 25, icon: 'sun', pop: 5 },
      { time: '17:00', temp: 22, icon: 'sun', pop: 5 },
      { time: '18:00', temp: 19, icon: 'partly-cloudy', pop: 10 },
      { time: '19:00', temp: 16, icon: 'moon', pop: 5 },
      { time: '20:00', temp: 14, icon: 'moon', pop: 0 },
    ],
    daily: [
      { day: 'Today', condition: 'Sunny Valleys', icon: 'sun', high: 27, low: 13, pop: 5 },
      { day: 'Sat', condition: 'Warm & Still', icon: 'sun', high: 29, low: 14, pop: 0 },
      { day: 'Sun', condition: 'Gentle Breeze', icon: 'wind', high: 25, low: 12, pop: 10 },
      { day: 'Mon', condition: 'Light Rain', icon: 'rain', high: 20, low: 11, pop: 70 },
      { day: 'Tue', condition: 'Crisp & Clear', icon: 'sun', high: 22, low: 12, pop: 15 },
      { day: 'Wed', condition: 'Sunny', icon: 'sun', high: 26, low: 13, pop: 5 },
      { day: 'Thu', condition: 'Pleasant', icon: 'partly-cloudy', high: 25, low: 14, pop: 10 },
    ],
  },
};

export function getFallbackWeather(query: string): WeatherCondition {
  const normalized = query.trim().toLowerCase();
  for (const [key, val] of Object.entries(DEFAULT_WEATHER_CITIES)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return val;
    }
  }

  // Generate realistic weather for any custom queried city
  const baseTemp = 18 + Math.floor((query.length * 7) % 15);
  return {
    city: query.charAt(0).toUpperCase() + query.slice(1),
    province: 'Regional Station Forecast',
    temp: baseTemp,
    condition: baseTemp > 25 ? 'Mostly Sunny' : 'Fair & Mild',
    icon: baseTemp > 25 ? 'sun' : 'partly-cloudy',
    high: baseTemp + 4,
    low: baseTemp - 7,
    humidity: 50 + (query.length * 3) % 40,
    windSpeed: 10 + (query.length * 2) % 25,
    feelsLike: baseTemp + 1,
    uvIndex: 6,
    airQuality: 'Good (35)',
    precipitationChance: (query.length * 9) % 50,
    hourly: [
      { time: 'Now', temp: baseTemp, icon: 'sun', pop: 10 },
      { time: '14:00', temp: baseTemp + 2, icon: 'sun', pop: 5 },
      { time: '16:00', temp: baseTemp + 3, icon: 'partly-cloudy', pop: 10 },
      { time: '18:00', temp: baseTemp - 1, icon: 'partly-cloudy', pop: 15 },
      { time: '20:00', temp: baseTemp - 4, icon: 'moon', pop: 10 },
    ],
    daily: [
      { day: 'Today', condition: 'Fair', icon: 'sun', high: baseTemp + 4, low: baseTemp - 7, pop: 10 },
      { day: 'Tomorrow', condition: 'Sunny', icon: 'sun', high: baseTemp + 5, low: baseTemp - 6, pop: 5 },
      { day: 'Day 3', condition: 'Cloudy', icon: 'cloud', high: baseTemp + 1, low: baseTemp - 8, pop: 30 },
      { day: 'Day 4', condition: 'Showers', icon: 'rain', high: baseTemp - 2, low: baseTemp - 9, pop: 60 },
      { day: 'Day 5', condition: 'Clear', icon: 'sun', high: baseTemp + 3, low: baseTemp - 6, pop: 10 },
    ],
  };
}
